### ISSUE TITLE
하나 질문드립니다.

### ISSUE THREAD

**Issue by juwomkim22** [potados99/melon-ticket-watcher#1]
$ npm start -- \
--product-id [멜론티켓 상품 ID] \
--schedule-no [(optional)공연 시간 ID]
--slack-webhook-url [알림 받을 슬랙 웹훅 URL] \
--poll-interval-millis [폴링 주기 밀리초]

실례가안된다면 예문좀 써주실수있을까요?

**Comment by juwomkim22** [comment]
> $ npm start -- --product-id [멜론티켓 상품 ID] --schedule-no [(optional)공연 시간 ID] --slack-webhook-url [알림 받을 슬랙 웹훅 URL] --poll-interval-millis [폴링 주기 밀리초]
> 
> 실례가안된다면 예문좀 써주실수있을까요?

슬랙 웹훅 적는데에서 자꾸 오류가발생해서 질문드립니다.

**Comment by potados99** [comment]
@juwomkim22 안녕하세요, 확인이 늦었네요 :)

~~~bash
$ npm start -- --product-id 206790 --schedule-no 100010 --slack-webhook-url https://hooks.slack.com/services/[생략]/[생략]/[생략] --poll-interval-millis 500
~~~

이렇게 사용하시면 됩니다. 혹시 어떤 에러가 발생하는지 자세하게 알려주신다면 원인도 찾아볼게요!

**Comment by syoungee** [comment]
```text
FetchError: invalid json response body at https://tktapi.melon.com/api/product/schedule/list.json?prodId=207126&pocCode=SC0003&perfTypeCode=GN0001&sellTypeCode=ST0001&v=1 reason: Unexpected end of JSON input
    at /Users/lia/Downloads/melon-ticket-watcher-main/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
```
저는 이런 에러가 뜨는데 해결 방법 여쭈어봐도 될까요?🥹

**Comment by syoungee** [comment]
`TypeError: Cannot read properties of undefined (reading 'perfDaylist')`
JSON.parse를 제거해도 뭔가 값을 못 가져오는 것 같아요ㅠ
