### ISSUE TITLE
저도 이슈남깁니다!

### ISSUE THREAD

**Issue by syoungee** [potados99/melon-ticket-watcher#2]
```
FetchError: invalid json response body at https://tktapi.melon.com/api/product/schedule/list.json?prodId=207126&pocCode=SC0003&perfTypeCode=GN0001&sellTypeCode=ST0001&v=1 reason: Unexpected end of JSON input
    at /Users/lia/Downloads/melon-ticket-watcher-main/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
```
저는 이런 에러가 뜨는데 해결 방법 여쭈어봐도 될까요?🥹

`TypeError: Cannot read properties of undefined (reading 'perfDaylist')`
JSON.parse를 제거해도 뭔가 값을 못 가져오는 것 같아요ㅠ
`https://tktapi.melon.com/tktapi/reservation/prodlimit.json?prodId=207126&pocCode=SC0002&perfTypeCode=GN0001&sellTypeCode=ST0001&v=1` 쉽지 않네요ㅠㅠ

아이유 서토콘 모니터링하고 싶은데 변수 몇가지 바꿔도 잘 동작하지가 않네요ㅠㅡㅠ

**Comment by potados99** [comment]
@syoungee 안녕하세요! 안타깝게도 이 melon-ticket-watcher는 회차가 많고 구역이 많은 큰 공연을 염두에 두고 개발되지 않았습니다ㅠㅡㅠ 그래서 아마 아이유 콘서트를 대상으로는 제대로 작동하지 않을거예요🥺 

저는 일단 급한대로 개발자 콘솔에서 사용하던 [스크립트를 크롬 확장으로 묶어서](https://github.com/potados99/melon-ticket-helper) 예매창을 직접 모니터링하고 있어요. 이것도 아직 문서나 설명도 없고 기능도 빈약하지만,,, 도움이 될까 싶어 올려봅니다. 감사합니다!

**Comment by syoungee** [comment]
@potados99 확인해볼게요! 감사합니다:) 이슈 남겨보는 게 처음인데 저도 무언가 만들어보고 싶다는 동기 부여가 또 하나 더 생겼습니다😊

**Comment by syoungee** [comment]
@potados99 저어 자리는 간간이 잡히는데 유효하지 않은 티켓이라고 뜨네요🥹
`https://zam.melon.com/ts.wseq?opcode=5003&key=~`
이 부분에서 5003을 5002로 보낼 수 있는 방법이 있을까요? secreteCode부분이랑 관련된 것 같은데 어떻게 하면 좋을까요?..

**Comment by potados99** [comment]
@syoungee 안녕하세요! zam.melon.com URL은 생소하지만 opcode와 key가 있는걸 보니 NetFunnel과 관련된 요청인 것 같네요 :) 

궁금함이 생겨 실례가 되지 않는다면 몇 가지만 여쭤보고 싶습니다😊 해당 요청이 일어나는 환경이 브라우저인가요? 아니면 HTTP 요청을 쏴주는 스크립트를 작성하신걸까요? 그리고 저 요청은 어떤 일을 하는 요청이고 어떤 결과가 기대될까요?

질문이 많아 죄송해요😅 알려주시면 저도 시간 나는 대로 같이 알아볼게요!

**Comment by syoungee** [comment]
@potados99
일단 저는 potados님 코드를 따로 변경하지 않았어요ㅎㅎ prepare함수의 주석을 제거하고 사용해야되는 걸까요??🤔

element탭에서 확인할 수 있는 부분이니까 브라우저 스크립트 부분일 것 같아요! 같이 알아봐주신다니 감사해요 

콘서트를 떠나 크롬 익스텐션의 세계가 너무 신기해서 계속 시도해보게 되네요~
`https://ticket.melon.com/performance/index.htm?prodId=207126`페이지에서 /를 누르면 팝업이 뜨면서 아래와 같은 alert가 뜨고 약간의 시간이 흐르면 좌석창과 자동방지 문자열 입력 모달이 뜹니다! 
`스크립트를 준비하는 중에 문제가 발생하였습니다: Cannot read properties of null (reading 'contentWindow')` alert를 닫고 /를 눌러주면 이 이미지와 같이 실행이 됩니다!
<img width="799" alt="image" src="https://user-images.githubusercontent.com/22606199/187072634-0ef713ec-928c-4dba-bd5b-9402a4f006da.png">
팝업창에서 /를 누르면 계속 새로고침을 하면서 빈 자리를 찾는데 빈 좌석을 찾게되어도 유효하지 않다는 alert가 뜨고 팝업이 꺼집니다. 5003이 뜨면 안되고 5002가 떠야 정상적으로 예매창으로 넘어가는 것으로 알고 있는데 새로고침 시 netfunnel이 요청을 너무 많이 넘긴 걸 인지하는 것 같아요. 어떻게 해결하면 좋을까요?
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/22606199/187072827-fa37d72d-b8a8-4d58-b627-f64cdd025326.png">
prepare함수에서 theSecretCode부분에서 주석을 제거해야될까요? 이 부분이 netFunnel의 설정을 어떻게 변경하는 건지 여쭤봅니다!

**Comment by potados99** [comment]
@syoungee 코멘트 감사해요! 어떤 부분 궁금해하시는지 알 것 같아요 :)

일단 결론부터 말씀드리자면 저도 같은 문제로 더이상 예매를 진행하지 못하고 있습니다😭

### `prepare` 함수가 하는 일

예매 당일날에 2만 7천명을 앞에 두고 한 시간 가량을 기다렸으나  몹시 슬프게도 브라우저가 멜론티켓의 팝업을 차단하여 예매창에 진입하지 못하는 일을 겪었습니다. 다행히 크롬 개발자 도구의 Network 탭을 열어서 대기가 끝나고 `5002` 응답과 함께 받은 key를 확보할 수 있었고, 그걸로 예매창을 띄울 수 있었어요🥹

예매창을 띄운다는 것은 사실 날짜 선택 화면에서 콘솔을 열고 `document.oneForm`에 파라미터를 채운 다음 submit하는 코드를 실행한 것인데요, 아래와 같아요:

```javascript
var oneStopWindowSize = getOneStopSize();
window.open("", "onstopForm", oneStopWindowSize);
var frm = document.oneForm;
var url = 'https://ticket.melon.com/reservation/popup/onestop.htm';
frm.action = url;
frm.target = 'onstopForm';
frm.prodId.value = '207126';
frm.pocCode.value = 'SC0002';
frm.scheduleNo.value = '100002';
frm.sellTypeCode.value = 'ST0001';
frm.tYn.value = 'Y';
frm.chk.value = encodeURIComponent('ED83ACt1ED9484e6mEBB8941p0EBA19DB2l8ockK9DB2l8ey');
frm.shuffleKey.value = encodeURIComponent('44446415606466425564');
frm.netfunnel_key.value = ":key=" + 'C71BD256F11853D1BEE541F51D46FBD7B51534B6EDF5F694BE3CBFECE8F94D62073088A33189674CEEF10B04294907E874DD8DBABEB97D9AA5D39A1C7C0D2E76DB13FAD32B624BE38411EE458BE513D08DA97010A2B964D5BCD4BB704A5FDFBF28DFBC9D0B556225BEADB9F6B79DA1022C30' + "&";
frm.submit();
```

이 코드(*예매창에 진입하는 코드*라고 부를게요)를 콘솔에 붙여넣으면 예매창이 열립니다. 물론 현재 시점에서 유효한 key를 넣어 주어야 해요. 즉, 유효한 key만 가지고 있으면 아무 때에 예매창을 열 수 있게 되었어요.

`prepare` 함수는 이 *예매창에 진입하는 코드*를 대기가 끝나는 시점에 `alert`과 `console.log`로 출력하도록 기존의 `window.reservationZAM` 함수를 비틀어주는(?) 친구입니다. `prepare`는 대기가 끝나는 시점에 `// 이렇게 쓰시라구요:`로 시작하는 *예매창 진입 코드*를 출력해줘요. 그게 바로 `theSecretCode` 변수의 내용입니다. *예매창을 열어주는 코드*를 뭐라 표현할까 고민하다가 그냥 `theSecretCode`라고 썼어요😅

 그리고 그렇게 출력된 `theSecretCode`, 또는 *예매창에 진입하는 코드*는 아무 때나 대기 없이 예매창에 다시 들어오고 싶을 때에 쓸 수 있지요👍

### `opcode`가 `5003`

[netfunnel.js](https://ticket.melon.com/resource/script/web/common/netfunnel.js)의 668번줄부터 `opcode`에 대한 정의가 나와서 가져와봤어요:

```javascript
    switch (b) {
    case 5101:
        c = "getTidchkEnter";
        break;
    case 5002:
        c = "chkEnter      ";
        break;
    case 5003:
        c = "aliveNotice   ";
        break;
    case 5004:
        c = "setComplete   ";
        break;
    default:
        c = "Unknown       "
    }
```

말씀주신 `https://zam.melon.com/ts.wseq?opcode=5003&key=~` 이 부분은 해당 스크립트를 열어볼 기회가 없어서 확실하지는 않지만, 아마 페이지가 열릴 때에 한 번 로드되어 서버에게 *나 잘 들어왔어~*라고 알릴 겸 다른 함수와 변수를 가져오는 역할을 맡고 있지 않을까 추측해봅니다. 따라서 예매창 진입 시도나 결제버튼 누르기와 같은 `5002`가 와야 성공인 동작들과는 조금 다른 성격인 것 같아요. 순전히 이름만 가지고 유추한 것이긴 하지만, 제 생각에는 아무 영향 없을 것 같아요!

### `"예매정보가 유효하지 않습니다. 예매창을 종료한 뒤 다시 시작해주세요."`

아마 수도 없이 보셨을 팝업 메시지예요... 예매 첫날 오후 11시 즈음부터 저리 뜨기 시작했습니다😭 이 부분은 멜론티켓 고객센터에 문의한 내용을 그대로 옮길게요 :)

<details>
<summary>첫 번째 문의</summary>

> 안녕하세요!    
> 다름이 아니라, 아이유 콘서트 취소표를 잡고 싶은데 예매 진행에 어려움을 겪고 있어 문의드립니다.
> 
> 회차 선택 -> 좌석 등급 선택 -> 구역 선택 -> 좌석 선택 후 "좌석 선택 완료" 버튼을 누르면 "예매정보가 유효하지 않습니다. 예매창을 종료한 뒤 다시 시작해주세요." 라고 뜹니다 ㅠ 빈 자리가 있어도 결제창으로 못 넘어가고 있어요.
> 
> 로그인도 다시 해보고 예매창도 다시 들어가보고 컴퓨터도 재부팅해보았는데 증상이 똑같습니다.
> 
> 어제 밤부터 그랬습니다. 혹시 새로고침을 너무 많이 눌러서 그런걸까요...? 
> 
> 도와주세요 ㅜ
</details>

<details>
<summary>첫 번째 답변</summary>

> 안녕하세요 고객님. 멜론티켓입니다.
> 
> 문의하신 내용에 대해 확인하여 본 결과, 티켓 오픈 시 동시접속자가 순간 다량 몰리게되어 좌석 선택 중복 또는 트래픽 초과가 발생된 것으로 파악되며, 좌석 선택 중복의 경우 먼저 결제를 완료하시는 고객님께서 좌석을 확보하시게되고 이후에는 확인하신 현상이 발생될 수 있습니다.
> 
> 간헐적으로 발생되는 현상에 대한 원인에는 여러가지가 있어 고객님의 경우 어느 곳에 해당하는지 정확한 파악이 어렵습니다.
> 
> 멜론티켓은 IE 또는 크롬 브라우저 최신 버전에 최적화 되어 있으며 타 브라우저는 구동은되나 정상적인 이용이 불가할 수 있습니다.
> 번거로우시겠지만 아래 내용을 확인 부탁드립니다.
> 
> *크롬 : 시크릿모드 사용불가, 타사쿠키차단옵션 체크해제, 크로스사이트 추적방지 체크해제
> *사파리 : 크로스사이트 추적방지 체크해제, 모든쿠키차단 체크해제
> 
> 답답하신 마음에 문의주셨으나 트래픽 초과 현상에 대해 보다 자세한 안내를 드리지 못해 죄송합니다.
> 
> 더 나은 서비스로 보답할 수 있도록 노력하는 멜론티켓이 되겠습니다.
> 감사합니다.
</details>

<details>
<summary>두 번째 질문</summary>

> 안녕하세요, 먼저 바쁘신 와중에 문의 확인하여 주셔서 정말 감사드립니다.
> 
> 다름이 아니라, 남겨주신 답변(파일 첨부했어요!)에 추가로 궁금한 사항이 생겨 문의드립니다.
> 
> 먼저, 해당 문제는 트래픽 문제는 아닌 것 같습니다. 문제가 간헐적이지 않고, 항상 발생합니다.
> 
> 또한 좌석 선택 중복 문제도 아닌 것 같습니다. 좌석 중복의 경우라면 "이미 선택된 좌석입니다" 에러가 발생하는 것으로 알고 있습니다.
> 
> 따라서 간헐적인 문제도, 트래픽 문제도 아닌, 기존에 발견되지 않았던 새로운 문제라고 생각하고 있습니다.
> 
> 해당 메시지("예매정보가 유효하지 않습니다")에 따르면, 이 에러는 페이지 값이나 파라미터가 누락 또는 유효하지 않은 값으로 변조되었을 때에만 나타나야 할 것으로 보입니다. 좌석 중복이라면 다른 에러가 발생해야 할 것입니다.
> 
> 그런데 의문스러운 것은, 아무런 조작이나 매크로 사용 없이 정상적으로 예매창에 접근한 경우인데도 불구하고 이러한 문제가 지속적으로 발생하고 있다는 점입니다.
> 
> 도저히 원인을 모르겠어서 좌석 선택 완료 버튼을 누르고 브라우저의 개발자 도구를 열어 네트워크 전송을 살펴보았는데, prodlimit.json 요청에 대한 응답이 T9110으로 오는 것을 확인하였습니다. 
> 
> 여태껏 멜론티켓을 오래 이용하면서 안정적인 트래픽 관리와 예매 시스템에 만족하였고, 다른 공연에서는 이러한 문제를 겪은 적이 없었습니다. 그래서 지금 너무 당혹스럽습니다...
> 
> 위에서 말씀드린 T9110 응답 건에 대하여 개발 담당자님의 기술적 답변을 부탁드려도 될까요? 지금 너무나 답답하고 궁금합니다. 번거로우시겠지만 꼭 부탁드리겠습니다. 항상 감사합니다. 좋은 하루 보내세요!
</details>

<details>
<summary>두 번째 답변</summary>

> 안녕하세요 고객님. 멜론티켓입니다. 
>
> 문의하신 내용에 대해 유관부서로 전달하여 상세 내용 확인을 요청하였습니다. 
> 
> 2022 IU CONCERT 〈The Golden Hour：오렌지 태양 아래〉 은 현재 예매를 위해 대기 및 접속을 시도하시는 고객님이 많은 상태로 예매 시 동시 접속자가 순간 다량 몰리게 되어 트래픽 초과 발생 영향으로 보입니다. 
> 
> 번거로우시겠지만 가급적 좌석선택 첫 진입 후 30분 이내 예매완료 부탁드립니다.
> 
> 좌석선택 창에 수분 동안 대기하시면 팝업 노출 후 예매 시도 화면으로 이동 될 수 있으며 이 경우 좌석 선택 화면을 종료한 후 재접속해주시기 바랍니다.
> 
> 멜론티켓은 IE 또는 크롬 브라우저 최신 버전에 최적화 되어 있으며 타 브라우저는 구동은 되나 정상적인 이용이 불가할 수 있사오니 참고 부탁드립니다.
> 
> 답답하신 마음에 문의 주셨으나 만족하실만한 답변드리지 못해 죄송합니다. 
> 
> 더 나은 서비스로 보답할 수 있도록 노력하는 멜론티켓이 되겠습니다. 
> 감사합니다.
</details>

저는 일단 반 포기 상태입니다.. ㅎㅎㅎ 모쪼록 방법 찾아 성공하시길 바라며 이만 줄일게요! 😁
